### ISSUE TITLE
'CDVWKWebViewEngine.h' file not found

### ISSUE THREAD

**Issue by nagaperla** [AraHovakimyan/cordova-plugin-wkwebviewxhrfix#1]
Recently, I updated my cordova app from cordova-ios@5.1.1 to @6.1.1 using the following steps -
cordova platform remove ios
cordova platform add ios@6.1.1

After adding a new platform work, I tried to build ios using cordova build ios. Then I'm getting this issue -
**Plugins/cordova-plugin-wkwebviewxhrfix/CDVWKWebViewEngine+FileXhrFix.h:9:9: fatal error:  'CDVWKWebViewEngine.h' file not found
#import <Cordova/CDVUserAgentUtil.h>
1 error generated.**

### **Version information**
Cordova: 10.0.0
Xcode: 12.2 (Build version: 12B45b)
cordova-ios: 6.1.1
Operating system: macOS
cordova-plugin-wkwebviewxhrfix: Latest version (Pulling from github repo source)

**Comment by AraHovakimyan** [comment]
Hi nagaperla,

The problem you mentioned has nothing to do with this plugin since there is nowhere to reference the file 'CDVWKWebViewEngine.h' in this plugin.
Probably your problem is related to the fact that your project uses plugin
 "cordova-plugin-wkwebviewxhrfix"
       instead of
"AraHovakimyan/cordova-plugin-wkwebviewxhrfix"
If you want your project to work correctly for Cordove-ios version 6.1.1
You need
1. First remove the cordova-plugin-wkwebviewxhrfix plugin by
    `cordova plugin rm cordova-plugin-wkwebviewxhrfix`

2.  Install plugin AraHovakimyan/cordova-plugin-wkwebviewxhrfix by 
    `cordova plugin add https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix`

Note:  If you have used the plugin "cordova-plugin-wkwebview-engine" before, you must also uninstall it as this plugin is unnecessary for Cordova-ios version 6.1.1
    `cordova plugin rm cordova-plugin-wkwebview-engine`

I hope you can fix your problem by following the above steps
