### ISSUE TITLE
Not working on iPad iOS 13+

### ISSUE THREAD

**Issue by mattprado21** [AraHovakimyan/cordova-plugin-wkwebviewxhrfix#4]
I have been building my application using monaca localkit with the following build setting versions and using this plugin, but seems  to be not working on iPad iOS 13 and 14. It works fine on all iOS versions on iPhone and iPad.

**iOS Platform**: 6.20
**Xcode**: 12.2
**Cordova**: 10(latest)

I hope you could try and verify this issue. Thank you!

**Comment by AraHovakimyan** [comment]
Hi @mattprado21 ,

To be honest, until this moment, I have not tested on "iPadOS".
Next Sunday, I will test the plugin on my project using a simulator with  "iPadOS", and then I will report about result. if the problem is with the plugin I will fix it.  Let's see what the result will be.

Thank you,

**Comment by mattprado21** [comment]
@AraHovakimyan Thank you much! But I have solved the issue already, I'm sorry, the cause was the phone gap loader is not updated not this plugin. 

https://github.com/apache/cordova-ios/issues/1138#issuecomment-900149182
