### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by benjamincxw** [AraHovakimyan/cordova-plugin-wkwebviewxhrfix#8]
Hi,
I've done the following to use this plugin, however, the old plugin is used([this](https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix)) instead of yours, is this as expected?
1. cordova plugin rm cordova-plugin-wkwebviewxhrfix
2. cordova plugin add https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix

App -> platforms -> ios -> App -> plugins
![WhatsApp Image 2022-12-09 at 11 43 26](https://user-images.githubusercontent.com/54138801/206619836-9d8c2b66-5137-423d-81bf-afd3a798ec32.jpg)

Would need your advice on this, thank you.

**Comment by AraHovakimyan** [comment]
Hi @benjamincxw  

I think that behavior is bug npm. For me works correctly.
I can only suggest options that can solve this problem.

You can check the package.json file in your project, maybe this file still contains a record containing the plugin name old still.
![Screenshot 2022-12-09 at 10 17 32](https://user-images.githubusercontent.com/70112075/206638705-77931e35-f127-4bef-a7ae-96aac0dced11.png)



Also If your project has the file package-lock.json, try to delete this file and then install it again, this file will be generated again. 
Maybe the problem is due to the fact that there are still entries in the old form in this file.

![Screenshot 2022-12-09 at 10 22 58](https://user-images.githubusercontent.com/70112075/206638803-8bb5dfd6-4254-429f-a2a0-0f213cd42b47.png)

![Screenshot 2022-12-09 at 10 21 58](https://user-images.githubusercontent.com/70112075/206638818-d007338d-5601-4773-9f1a-5b7d1c4e9fe1.png)


If it helps please let me know.

**Comment by AraHovakimyan** [comment]
Hi @benjamincxw 
I think that behavior is bug npm. For me works correctly.
I can only suggest options that can solve this problem.

You can check the **package.json** file in your project, maybe this file still contains a record containing the plugin name old still.
![Screenshot 2022-12-09 at 10 17 32](https://user-images.githubusercontent.com/70112075/206639843-63a09516-eda6-4201-a49c-b337f50bb0a6.png)


If your project has the file **package-lock.json**, try to delete this file and then install it again, this file will be generated again. 
Maybe the problem is due to the fact that there are still entries in the old form in this file.
![Screenshot 2022-12-09 at 10 22 58](https://user-images.githubusercontent.com/70112075/206639902-74b5d110-285e-4461-9808-fe4c89883c69.png)
![Screenshot 2022-12-09 at 10 21 58](https://user-images.githubusercontent.com/70112075/206639921-35f651e1-3306-4eec-a7a8-44f39961a672.png)
etc.

If it helps let me know

Thanks.

**Comment by AraHovakimyan** [comment]
Try to use this fork 
`cordova plugin add https://github.com/IsraelHikingMap/cordova-plugin-wkwebviewxhrfix`

Please let me know if this approach will help you to fix your issue.

Based on discussion
https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix/issues/5#issuecomment-1162193487

**Comment by AraHovakimyan** [comment]
Maybe you have a problem similar to the one listed in this issue and maybe discussion can help you to solve your issue.

https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix/issues/10#issuecomment-1551089169
